# Build from the Python 3.8 slim image
FROM ubuntu:latest

# Create a environment variable called db_name
ENV db_name="staff_database"

# Create a environment variable called db_password
ENV db_password "legendofkorra"